const express=require('express'),fs=require('fs'),path=require('path'),ExcelJS=require('exceljs');
const app=express(); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
const DB=path.join(__dirname,'data.json');
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[{name:"Lê Hiền",password:"1234",role:"employee"},{name:"Linh",password:"1234",role:"employee"},{name:"Admin",password:"admin123",role:"admin"}],records:[]},null,2));
const read=()=>JSON.parse(fs.readFileSync(DB)); const write=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));
const sessions=new Map();
function auth(req,res,next){const s=sessions.get(req.headers.authorization||''); if(!s)return res.status(401).json({error:'Chưa đăng nhập'}); req.user=s;next()}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Không có quyền'});next()}
app.post('/api/login',(req,res)=>{const db=read(),u=db.users.find(x=>x.name===req.body.name&&x.password===req.body.password);if(!u)return res.status(401).json({error:'Sai tài khoản hoặc mật khẩu'});const token=Math.random().toString(36).slice(2)+Date.now();sessions.set(token,{name:u.name,role:u.role});res.json({token,name:u.name,role:u.role})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.post('/api/checkin',auth,(req,res)=>{if(req.user.role==='admin')return res.status(403).json({error:'Admin không chấm công bằng tài khoản quản trị'});const db=read(),now=new Date(),date=now.toLocaleDateString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}),time=now.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Ho_Chi_Minh'});let r=db.records.find(x=>x.user===req.user.name&&x.date===date);if(r&&r.in)return res.status(409).json({error:'Đã chấm công vào hôm nay'});if(!r)db.records.push({user:req.user.name,date,in:time,out:''});else r.in=time;write(db);res.json({ok:true})});
app.post('/api/checkout',auth,(req,res)=>{if(req.user.role==='admin')return res.status(403).json({error:'Không hợp lệ'});const db=read(),now=new Date(),date=now.toLocaleDateString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}),time=now.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Ho_Chi_Minh'}),r=db.records.find(x=>x.user===req.user.name&&x.date===date);if(!r||!r.in)return res.status(409).json({error:'Chưa chấm công vào'});if(r.out)return res.status(409).json({error:'Đã chấm công ra'});r.out=time;write(db);res.json({ok:true})});
app.get('/api/my-records',auth,(req,res)=>res.json(read().records.filter(x=>x.user===req.user.name).reverse()));
app.get('/api/records',auth,admin,(req,res)=>res.json(read().records.slice().reverse()));
app.get('/api/export',auth,admin,async(req,res)=>{const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Cham cong');ws.columns=[{header:'Nhân viên',key:'user',width:22},{header:'Ngày',key:'date',width:14},{header:'Giờ vào',key:'in',width:14},{header:'Giờ ra',key:'out',width:14},{header:'Trạng thái',key:'status',width:18}];read().records.forEach(r=>ws.addRow({...r,status:r.out?'Hoàn tất':'Chưa chấm ra'}));res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="Cham_cong_Duong_Trieu_Phat.xlsx"');await wb.xlsx.write(res);res.end()});
app.listen(3000,()=>console.log('DTP attendance running on http://localhost:3000'));